//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deserializer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Inputs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Inputs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Deserializer.Inputs", typeof(Inputs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;has_title&quot;: true,
        ///  &quot;title&quot;: &quot;GoodLuck&quot;,
        ///  &quot;entries&quot;: {
        ///    &quot;/gettingstarted.pdf&quot;: {
        ///      &quot;thumb_exists&quot;: false,
        ///      &quot;path&quot;: &quot;/GettingStarted.pdf&quot;,
        ///      &quot;client_mtime&quot;: &quot;Wed, 08 Jan 2014 18:00:54+0000&quot;,
        ///      &quot;bytes&quot;: 249159
        ///    },
        ///    &quot;/task.jpg&quot;: {
        ///      &quot;thumb_exists&quot;: true,
        ///      &quot;path&quot;: &quot;/Task.jpg&quot;,
        ///      &quot;client_mtime&quot;: &quot;Tue, 14 Jan 2014 05:53:57+0000&quot;,
        ///      &quot;bytes&quot;: 207696
        ///    }
        ///  }
        ///}.
        /// </summary>
        internal static string Alternative {
            get {
                return ResourceManager.GetString("Alternative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;has_title&quot;: true,
        ///  &quot;title&quot;: &quot;GoodLuck&quot;,
        ///  &quot;entries&quot;: [
        ///    [
        ///      &quot;/gettingstarted.pdf&quot;,
        ///      {
        ///        &quot;thumb_exists&quot;: false,
        ///        &quot;path&quot;: &quot;/GettingStarted.pdf&quot;,
        ///        &quot;client_mtime&quot;: &quot;Wed, 08 Jan 2014 18:00:54+0000&quot;,
        ///        &quot;bytes&quot;: 249159
        ///      }
        ///    ],
        ///    [
        ///      &quot;/task.jpg&quot;,
        ///      {
        ///        &quot;thumb_exists&quot;: true,
        ///        &quot;path&quot;: &quot;/Task.jpg&quot;,
        ///        &quot;client_mtime&quot;: &quot;Tue, 14 Jan 2014 05:53:57+0000&quot;,
        ///        &quot;bytes&quot;: 207696
        ///      }
        ///    ]
        ///  ]
        ///}.
        /// </summary>
        internal static string Original {
            get {
                return ResourceManager.GetString("Original", resourceCulture);
            }
        }
    }
}
